version: "3"
services:
  dotstudio_web:
    build: .
    volumes:
      - ./web:/var/www/html/dotstudio
    ports:
      - 8081:8081
      - 3000:3000
    depends_on:
      - dotstudio_database
  dotstudio_database:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - 5432:5432
